import { InsertPetType } from "./schema";

export interface PetTypeData extends Omit<InsertPetType, "id"> {
  petId: string;
  name: string;
  description: string;
  emoji: string;
  iconPath: string;
  rarity: "common" | "uncommon" | "rare" | "epic" | "legendary";
  hungerDecay: number;
  hygieneDecay: number;
  energyDecay: number;
  funDecay: number;
  adoptionCost: number;
  isCustom: boolean;
  friendlyTo: string[];
  hostileTo: string[];
}

export const STATIC_PET_TYPES: PetTypeData[] = [
  {
    petId: "karen_lol",
    name: "Karen",
    description: "O.M.G JUST SYBAU",
    emoji: "👽",
    iconPath: "karen.png",
    rarity: "epic",
    hungerDecay: 8,
    hygieneDecay: 5,
    energyDecay: 10,
    funDecay: 1,
    adoptionCost: 75000,
    isCustom: true,
    friendlyTo: [],
    hostileTo: [
      "dog",
      "cat",
      "snake",
      "dragon",
      "unicorn",
      "cupid",
      "jack-frost",
      "phoenix",
    ],
  },

  {
    petId: "alien",
    name: "Alien",
    description:
      "An otherworldly companion from beyond the stars. Mysterious and fascinating.",
    emoji: "👽",
    iconPath: "alien.png",
    rarity: "epic",
    hungerDecay: 2,
    hygieneDecay: 2,
    energyDecay: 2,
    funDecay: 2,
    adoptionCost: 75000,
    isCustom: false,
    friendlyTo: ["dragon", "unicorn", "cupid", "jack-frost", "phoenix"],
    hostileTo: ["dog", "cat", "snake"],
  },
  {
    petId: "axolotl",
    name: "Axolotl",
    description:
      "A cute aquatic salamander with regenerative abilities. Adorably unique!",
    emoji: "🦎",
    iconPath: "axolotle.png",
    rarity: "rare",
    hungerDecay: 3,
    hygieneDecay: 4,
    energyDecay: 3,
    funDecay: 3,
    adoptionCost: 35000,
    isCustom: false,
    friendlyTo: ["penguin", "blobfish", "duck", "turtle", "crab", "frog"],
    hostileTo: ["cat", "snake", "spider"],
  },
  {
    petId: "justins_burger",
    name: "Justin's Half Eaten Burger",
    description:
      "Honestly suprising how many half eaten foods he leaves laying around considering his weight.",
    emoji: "🦎",
    iconPath: "justinsburger.png",
    rarity: "legendary",
    hungerDecay: 1,
    hygieneDecay: 1,
    energyDecay: 1,
    funDecay: 1,
    adoptionCost: 1000000000,
    isCustom: true,
    friendlyTo: ["penguin", "blobfish", "duck", "turtle", "crab", "frog"],
    hostileTo: ["cat", "snake", "spider"],
  },
  {
    petId: "bird",
    name: "Bird",
    description: "A cheerful feathered friend that loves to sing and soar.",
    emoji: "🐦",
    iconPath: "bird.png",
    rarity: "common",
    hungerDecay: 5,
    hygieneDecay: 5,
    energyDecay: 5,
    funDecay: 5,
    adoptionCost: 7500,
    isCustom: false,
    friendlyTo: ["duck", "penguin", "parrot", "chicken", "owl"],
    hostileTo: ["cat", "snake", "fox"],
  },
  {
    petId: "bob",
    name: "Bob",
    description: "The legendary Bob. Nobody knows what Bob is, but Bob is Bob.",
    emoji: "🔴",
    iconPath: "blob.gif",
    rarity: "legendary",
    hungerDecay: 1,
    hygieneDecay: 1,
    energyDecay: 1,
    funDecay: 1,
    adoptionCost: 150000,
    isCustom: false,
    friendlyTo: ["pepe", "rock", "krampus"],
    hostileTo: [],
  },
  {
    petId: "blobfish",
    name: "Blobfish",
    description: "The saddest looking fish in the ocean, but it loves you!",
    emoji: "🐠",
    iconPath: "blobfish.png",
    rarity: "uncommon",
    hungerDecay: 4,
    hygieneDecay: 4,
    energyDecay: 4,
    funDecay: 4,
    adoptionCost: 15000,
    isCustom: false,
    friendlyTo: ["axolotl", "penguin", "turtle", "crab", "octopus"],
    hostileTo: ["cat", "bird"],
  },
  {
    petId: "baby",
    name: "Baby",
    description:
      "This is a virtual baby. Not a real baby. Needed to clear that up for some people. (Scout)",
    emoji: "🐠",
    iconPath: "baby.png",
    rarity: "rare",
    hungerDecay: 3,
    hygieneDecay: 3,
    energyDecay: 4,
    funDecay: 7,
    adoptionCost: 15000,
    isCustom: false,
    friendlyTo: ["axolotl", "penguin", "turtle", "crab", "octopus"],
    hostileTo: ["cat", "bird", "dog", "fox", "snake"],
  },
  {
    petId: "bunny",
    name: "Bunny",
    description: "A fluffy little hopper with endless energy and cuteness.",
    emoji: "🐰",
    iconPath: "bunny.png",
    rarity: "common",
    hungerDecay: 5,
    hygieneDecay: 5,
    energyDecay: 5,
    funDecay: 5,
    adoptionCost: 6000,
    isCustom: false,
    friendlyTo: ["hamster", "guinea-pig", "capybara", "pig", "deer"],
    hostileTo: ["fox", "snake", "wolf"],
  },
  {
    petId: "capybara",
    name: "Capybara",
    description: "The most chill rodent ever. Literally friends with everyone.",
    emoji: "🦫",
    iconPath: "capybara.png",
    rarity: "rare",
    hungerDecay: 3,
    hygieneDecay: 3,
    energyDecay: 3,
    funDecay: 3,
    adoptionCost: 40000,
    isCustom: false,
    friendlyTo: [
      "bunny",
      "hamster",
      "guinea-pig",
      "monkey",
      "pig",
      "duck",
      "bird",
      "cat",
      "dog",
    ],
    hostileTo: [],
  },
  {
    petId: "dead_guy",
    name: "Skele",
    description: "The most chill dead guy, like ever.",
    emoji: "🦫",
    iconPath: "deadguy.gif",
    rarity: "epic",
    hungerDecay: 1,
    hygieneDecay: 1,
    energyDecay: 1,
    funDecay: 6,
    adoptionCost: 40000,
    isCustom: false,
    friendlyTo: [
      "bunny",
      "hamster",
      "guinea-pig",
      "monkey",
      "pig",
      "duck",
      "bird",
      "cat",
      "dog",
      "ghost",
      "jack-o-lantern",
      "krampus",
      "catgirl",
      "dragon",
      "unicorn",
      "phoenix",
      "cupid",
      "jack-frost",
      "alien",
      "pepe",
      "bob",
      "nyan-cat",
      "doge",
      "demon",
    ],
    hostileTo: [],
  },

  {
    petId: "cat",
    name: "Cat",
    description:
      "An independent feline that may or may not acknowledge your existence.",
    emoji: "🐱",
    iconPath: "cat.png",
    rarity: "common",
    hungerDecay: 5,
    hygieneDecay: 5,
    energyDecay: 5,
    funDecay: 5,
    adoptionCost: 5000,
    isCustom: false,
    friendlyTo: ["catgirl", "tiger", "lion", "panther"],
    hostileTo: ["dog", "bird", "hamster", "mouse"],
  },
  {
    petId: "catgirl",
    name: "Catgirl",
    description: "Nya~ A mysterious anime companion with cat-like features.",
    emoji: "🐱‍👤",
    iconPath: "catgirl.png",
    rarity: "rare",
    hungerDecay: 3,
    hygieneDecay: 3,
    energyDecay: 3,
    funDecay: 3,
    adoptionCost: 45000,
    isCustom: false,
    friendlyTo: ["cat", "dog", "bunny", "fox"],
    hostileTo: ["snake", "spider"],
  },
  {
    petId: "crab",
    name: "Crab",
    description:
      "A snappy crustacean with impressive pinchers. Watch your fingers!",
    emoji: "🦀",
    iconPath: "crab.png",
    rarity: "uncommon",
    hungerDecay: 4,
    hygieneDecay: 4,
    energyDecay: 4,
    funDecay: 4,
    adoptionCost: 12000,
    isCustom: false,
    friendlyTo: ["blobfish", "axolotl", "octopus", "turtle"],
    hostileTo: ["bird", "cat"],
  },
  {
    petId: "cupid",
    name: "Cupid",
    description:
      "A divine being of love who shoots arrows straight to your heart.",
    emoji: "💘",
    iconPath: "cupid.png",
    rarity: "epic",
    hungerDecay: 2,
    hygieneDecay: 2,
    energyDecay: 2,
    funDecay: 2,
    adoptionCost: 80000,
    isCustom: false,
    friendlyTo: ["unicorn", "phoenix", "dragon", "alien"],
    hostileTo: ["krampus", "demon"],
  },
  {
    petId: "dog",
    name: "Dog",
    description:
      "Man's best friend! Loyal, loving, and always happy to see you.",
    emoji: "🐕",
    iconPath: "dog.png",
    rarity: "common",
    hungerDecay: 5,
    hygieneDecay: 5,
    energyDecay: 5,
    funDecay: 5,
    adoptionCost: 5000,
    isCustom: false,
    friendlyTo: ["wolf", "fox", "pig", "bunny"],
    hostileTo: ["cat", "snake"],
  },
  {
    petId: "dragon",
    name: "Dragon",
    description: "A majestic fire-breathing beast of legend. Handle with care!",
    emoji: "🐉",
    iconPath: "dragon.png",
    rarity: "epic",
    hungerDecay: 2,
    hygieneDecay: 2,
    energyDecay: 2,
    funDecay: 2,
    adoptionCost: 90000,
    isCustom: false,
    friendlyTo: ["phoenix", "alien", "unicorn", "griffin"],
    hostileTo: ["knight", "ice-dragon"],
  },
  {
    petId: "duck",
    name: "Duck",
    description: "Quack quack! A waterfowl that waddles into your heart.",
    emoji: "🦆",
    iconPath: "duck.png",
    rarity: "common",
    hungerDecay: 5,
    hygieneDecay: 5,
    energyDecay: 5,
    funDecay: 5,
    adoptionCost: 6500,
    isCustom: false,
    friendlyTo: ["bird", "penguin", "swan", "goose", "chicken"],
    hostileTo: ["fox", "cat"],
  },
  {
    petId: "fox",
    name: "Fox",
    description: "A cunning and playful creature with a bushy tail.",
    emoji: "🦊",
    iconPath: "fox.png",
    rarity: "uncommon",
    hungerDecay: 4,
    hygieneDecay: 4,
    energyDecay: 4,
    funDecay: 4,
    adoptionCost: 18000,
    isCustom: false,
    friendlyTo: ["dog", "wolf", "catgirl"],
    hostileTo: ["bunny", "bird", "chicken"],
  },
  {
    petId: "gecko",
    name: "Gecko",
    description:
      "A small lizard that can climb walls and save you money on insurance.",
    emoji: "🦎",
    iconPath: "tbd.png",
    rarity: "uncommon",
    hungerDecay: 4,
    hygieneDecay: 4,
    energyDecay: 4,
    funDecay: 4,
    adoptionCost: 14000,
    isCustom: false,
    friendlyTo: ["snake", "turtle", "frog", "chameleon"],
    hostileTo: ["cat", "bird"],
  },
  {
    petId: "hamster",
    name: "Hamster",
    description: "A tiny ball of fluff that runs on a wheel all day long.",
    emoji: "🐹",
    iconPath: "hamster.png",
    rarity: "common",
    hungerDecay: 5,
    hygieneDecay: 5,
    energyDecay: 5,
    funDecay: 5,
    adoptionCost: 7000,
    isCustom: false,
    friendlyTo: ["bunny", "guinea-pig", "mouse", "capybara"],
    hostileTo: ["cat", "snake", "owl"],
  },
  {
    petId: "jack-frost",
    name: "Jack Frost",
    description:
      "A chilly winter spirit that brings the frost and fun wherever it goes.",
    emoji: "❄️",
    iconPath: "jackfrost.gif",
    rarity: "epic",
    hungerDecay: 2,
    hygieneDecay: 2,
    energyDecay: 2,
    funDecay: 2,
    adoptionCost: 85000,
    isCustom: false,
    friendlyTo: ["ice-dragon", "penguin", "polar-bear", "snowman"],
    hostileTo: ["dragon", "phoenix", "jack-o-lantern"],
  },
  {
    petId: "jack-o-lantern",
    name: "Jack O' Lantern",
    description: "A spooky Halloween pumpkin companion that glows in the dark.",
    emoji: "🎃",
    iconPath: "jackolantern.gif",
    rarity: "epic",
    hungerDecay: 2,
    hygieneDecay: 2,
    energyDecay: 2,
    funDecay: 2,
    adoptionCost: 85000,
    isCustom: false,
    friendlyTo: ["krampus", "demon", "ghost", "witch-cat"],
    hostileTo: ["jack-frost", "cupid"],
  },
  {
    petId: "koala",
    name: "Koala",
    description: "A sleepy marsupial that loves eucalyptus and long naps.",
    emoji: "🐨",
    iconPath: "koala.gif",
    rarity: "uncommon",
    hungerDecay: 4,
    hygieneDecay: 4,
    energyDecay: 4,
    funDecay: 4,
    adoptionCost: 16000,
    isCustom: false,
    friendlyTo: ["opossum", "kangaroo", "wombat"],
    hostileTo: ["snake", "spider"],
  },
  {
    petId: "krampus",
    name: "Krampus",
    description:
      "The legendary Christmas demon. Better behave or face the consequences!",
    emoji: "👹",
    iconPath: "kracken.png",
    rarity: "legendary",
    hungerDecay: 1,
    hygieneDecay: 1,
    energyDecay: 1,
    funDecay: 1,
    adoptionCost: 175000,
    isCustom: false,
    friendlyTo: ["demon", "jack-o-lantern", "ghost"],
    hostileTo: ["cupid", "unicorn", "santa"],
  },
  {
    petId: "monkey",
    name: "Monkey",
    description: "A mischievous primate that loves bananas and causing chaos.",
    emoji: "🐵",
    iconPath: "monkey.png",
    rarity: "uncommon",
    hungerDecay: 4,
    hygieneDecay: 4,
    energyDecay: 4,
    funDecay: 4,
    adoptionCost: 13000,
    isCustom: false,
    friendlyTo: ["capybara", "parrot", "gorilla"],
    hostileTo: ["snake", "tiger"],
  },
  {
    petId: "opossum",
    name: "Opossum",
    description: "A misunderstood marsupial that plays dead when scared.",
    emoji: "🦡",
    iconPath: "possum.png",
    rarity: "common",
    hungerDecay: 5,
    hygieneDecay: 5,
    energyDecay: 5,
    funDecay: 5,
    adoptionCost: 8000,
    isCustom: false,
    friendlyTo: ["koala", "raccoon", "skunk"],
    hostileTo: ["dog", "fox"],
  },
  {
    petId: "pepe",
    name: "Pepe",
    description: "The rarest of meme frogs. A true legend among collectors.",
    emoji: "🐸",
    iconPath: "pepe.png",
    rarity: "legendary",
    hungerDecay: 1,
    hygieneDecay: 1,
    energyDecay: 1,
    funDecay: 1,
    adoptionCost: 200000,
    isCustom: false,
    friendlyTo: ["bob", "rock", "doge"],
    hostileTo: [],
  },
  {
    petId: "rock",
    name: "Rock",
    description:
      "A legendary pet rock. The pioneers used to ride these babies for miles!",
    emoji: "🗿",
    iconPath: "rock.png",
    rarity: "legendary",
    hungerDecay: 1,
    hygieneDecay: 1,
    energyDecay: 1,
    funDecay: 1,
    adoptionCost: 125000,
    isCustom: false,
    friendlyTo: ["bob", "pepe", "garden-gnome"],
    hostileTo: [],
  },
  {
    petId: "snake",
    name: "Snake",
    description: "A slithery serpent with mesmerizing scales.",
    emoji: "🐍",
    iconPath: "snake.gif",
    rarity: "uncommon",
    hungerDecay: 4,
    hygieneDecay: 4,
    energyDecay: 4,
    funDecay: 4,
    adoptionCost: 17000,
    isCustom: false,
    friendlyTo: ["gecko", "spider", "funnel-web-spider"],
    hostileTo: ["bunny", "hamster", "bird", "mouse"],
  },
  {
    petId: "turtle",
    name: "Turtle",
    description: "Slow and steady wins the race! A patient and wise companion.",
    emoji: "🐢",
    iconPath: "turtle.png",
    rarity: "uncommon",
    hungerDecay: 4,
    hygieneDecay: 4,
    energyDecay: 4,
    funDecay: 4,
    adoptionCost: 11000,
    isCustom: false,
    friendlyTo: ["blobfish", "axolotl", "crab", "gecko", "sea-turtle"],
    hostileTo: ["cat", "dog"],
  },
  {
    petId: "unicorn",
    name: "Unicorn",
    description: "A magical horse with a sparkly horn. Pure enchantment!",
    emoji: "🦄",
    iconPath: "tbd.png",
    rarity: "epic",
    hungerDecay: 2,
    hygieneDecay: 2,
    energyDecay: 2,
    funDecay: 2,
    adoptionCost: 95000,
    isCustom: false,
    friendlyTo: ["phoenix", "dragon", "cupid", "pegasus"],
    hostileTo: ["krampus", "demon"],
  },
  {
    petId: "penguin",
    name: "Penguin",
    description: "A dapper bird in a tuxedo that waddles with style.",
    emoji: "🐧",
    iconPath: "penguin.png",
    rarity: "rare",
    hungerDecay: 3,
    hygieneDecay: 3,
    energyDecay: 3,
    funDecay: 3,
    adoptionCost: 30000,
    isCustom: false,
    friendlyTo: ["king-penguin", "duck", "bird", "polar-bear", "seal"],
    hostileTo: ["fox", "orca"],
  },
  {
    petId: "pig",
    name: "Pig",
    description: "An adorable oinker that loves mud baths and snacks.",
    emoji: "🐷",
    iconPath: "tbd.png",
    rarity: "common",
    hungerDecay: 5,
    hygieneDecay: 5,
    energyDecay: 5,
    funDecay: 5,
    adoptionCost: 9000,
    isCustom: false,
    friendlyTo: ["dog", "bunny", "capybara", "cow"],
    hostileTo: ["wolf", "fox"],
  },
  {
    petId: "king-penguin",
    name: "King Penguin",
    description: "The most regal of all penguins. Royalty on ice!",
    emoji: "👑🐧",
    iconPath: "penguin.png",
    rarity: "epic",
    hungerDecay: 2,
    hygieneDecay: 2,
    energyDecay: 2,
    funDecay: 2,
    adoptionCost: 100000,
    isCustom: false,
    friendlyTo: ["penguin", "polar-bear", "ice-dragon", "seal"],
    hostileTo: ["orca", "leopard-seal"],
  },
  {
    petId: "phoenix",
    name: "Phoenix",
    description:
      "An immortal firebird that rises from its own ashes. Legendary beauty!",
    emoji: "🔥🦅",
    iconPath: "phoenix.gif",
    rarity: "legendary",
    hungerDecay: 1,
    hygieneDecay: 1,
    energyDecay: 1,
    funDecay: 1,
    adoptionCost: 180000,
    isCustom: false,
    friendlyTo: ["dragon", "unicorn", "cupid", "griffin"],
    hostileTo: ["jack-frost", "ice-dragon"],
  },
  {
    petId: "mewtwo",
    name: "Mewtwo",
    description:
      "A genetically engineered psychic powerhouse. Gotta catch this one!",
    emoji: "🧬💜",
    iconPath: "tbd.png",
    rarity: "legendary",
    hungerDecay: 1,
    hygieneDecay: 1,
    energyDecay: 1,
    funDecay: 1,
    adoptionCost: 250000,
    isCustom: false,
    friendlyTo: ["alien", "pikachu", "charizard"],
    hostileTo: ["mew"],
  },
  {
    petId: "funnel-web-spider",
    name: "Funnel Web Spider",
    description:
      "One of the deadliest spiders in the world. Handle with extreme caution!",
    emoji: "🕷️",
    iconPath: "spider.gif",
    rarity: "rare",
    hungerDecay: 3,
    hygieneDecay: 3,
    energyDecay: 3,
    funDecay: 3,
    adoptionCost: 42000,
    isCustom: false,
    friendlyTo: ["snake", "scorpion", "tarantula"],
    hostileTo: ["bird", "cat", "gecko"],
  },
  {
    petId: "garden-gnome",
    name: "Garden Gnome",
    description:
      "A mystical lawn ornament that comes to life at night. Protector of gardens!",
    emoji: "🧙‍♂️",
    iconPath: "gardengnome.gif",
    rarity: "rare",
    hungerDecay: 3,
    hygieneDecay: 3,
    energyDecay: 3,
    funDecay: 3,
    adoptionCost: 38000,
    isCustom: false,
    friendlyTo: ["rock", "fairy", "dwarf", "elf"],
    hostileTo: ["dragon", "troll"],
  },
  {
    petId: "wolf",
    name: "Wolf",
    description:
      "A fierce and loyal pack hunter. Howls at the moon with pride.",
    emoji: "🐺",
    iconPath: "tbd.png",
    rarity: "rare",
    hungerDecay: 3,
    hygieneDecay: 3,
    energyDecay: 3,
    funDecay: 3,
    adoptionCost: 36000,
    isCustom: false,
    friendlyTo: ["dog", "fox", "dire-wolf"],
    hostileTo: ["bunny", "sheep", "pig"],
  },
  {
    petId: "panda",
    name: "Panda",
    description: "A gentle giant that munches bamboo all day. Adorably clumsy!",
    emoji: "🐼",
    iconPath: "panda.png",
    rarity: "rare",
    hungerDecay: 3,
    hygieneDecay: 3,
    energyDecay: 3,
    funDecay: 3,
    adoptionCost: 50000,
    isCustom: false,
    friendlyTo: ["red-panda", "koala", "capybara"],
    hostileTo: ["tiger", "leopard"],
  },
  {
    petId: "red-panda",
    name: "Red Panda",
    description:
      "A fluffy tree-dwelling cutie. Not actually a panda, but definitely adorable!",
    emoji: "🦊🔴",
    iconPath: "tbd.png",
    rarity: "uncommon",
    hungerDecay: 4,
    hygieneDecay: 4,
    energyDecay: 4,
    funDecay: 4,
    adoptionCost: 22000,
    isCustom: false,
    friendlyTo: ["panda", "fox", "raccoon"],
    hostileTo: ["snow-leopard", "eagle"],
  },
  {
    petId: "raccoon",
    name: "Raccoon",
    description:
      "A masked bandit with nimble paws. Will steal your heart (and your snacks)!",
    emoji: "🦝",
    iconPath: "raccon.png",
    rarity: "uncommon",
    hungerDecay: 4,
    hygieneDecay: 4,
    energyDecay: 4,
    funDecay: 4,
    adoptionCost: 19000,
    isCustom: false,
    friendlyTo: ["opossum", "red-panda", "skunk"],
    hostileTo: ["dog", "cat"],
  },
  {
    petId: "owl",
    name: "Owl",
    description:
      "A wise nocturnal hunter with piercing eyes. Hoots in the night!",
    emoji: "🦉",
    iconPath: "owl.gif",
    rarity: "uncommon",
    hungerDecay: 4,
    hygieneDecay: 4,
    energyDecay: 4,
    funDecay: 4,
    adoptionCost: 20000,
    isCustom: false,
    friendlyTo: ["bird", "eagle", "raven"],
    hostileTo: ["mouse", "snake", "hamster"],
  },
  {
    petId: "parrot",
    name: "Parrot",
    description:
      "A colorful chatterbox that repeats everything you say. Squawk!",
    emoji: "🦜",
    iconPath: "tbd.png",
    rarity: "uncommon",
    hungerDecay: 4,
    hygieneDecay: 4,
    energyDecay: 4,
    funDecay: 4,
    adoptionCost: 21000,
    isCustom: false,
    friendlyTo: ["bird", "monkey", "toucan"],
    hostileTo: ["cat", "snake"],
  },
  {
    petId: "frog",
    name: "Frog",
    description:
      "A hoppy amphibian that catches flies with its long tongue. Ribbit!",
    emoji: "🐸",
    iconPath: "frog.png",
    rarity: "common",
    hungerDecay: 5,
    hygieneDecay: 5,
    energyDecay: 5,
    funDecay: 5,
    adoptionCost: 5500,
    isCustom: false,
    friendlyTo: ["axolotl", "turtle", "gecko", "salamander"],
    hostileTo: ["snake", "bird"],
  },
  {
    petId: "bee",
    name: "Bee",
    description:
      "A busy buzzer that makes sweet honey. According to all known laws of aviation...",
    emoji: "🐝",
    iconPath: "bee.gif",
    rarity: "common",
    hungerDecay: 5,
    hygieneDecay: 5,
    energyDecay: 5,
    funDecay: 5,
    adoptionCost: 8500,
    isCustom: false,
    friendlyTo: ["butterfly", "ladybug", "ant"],
    hostileTo: ["spider", "wasp", "hornet"],
  },
  {
    petId: "maccades_taco",
    name: "McCade's Taco",
    description: "Gee, who would have guessed he likes tacos.",
    emoji: "🐝",
    iconPath: "tacoguy.png",
    rarity: "legendary",
    hungerDecay: 1,
    hygieneDecay: 1,
    energyDecay: 1,
    funDecay: 1,
    adoptionCost: 1000000000,
    isCustom: true,
    friendlyTo: ["butterfly", "ladybug", "ant"],
    hostileTo: ["spider", "wasp", "hornet"],
  },
  {
    petId: "butterfly",
    name: "Butterfly",
    description:
      "A delicate fluttering beauty with colorful wings. Nature's artwork!",
    emoji: "🦋",
    iconPath: "tbd.png",
    rarity: "common",
    hungerDecay: 5,
    hygieneDecay: 5,
    energyDecay: 5,
    funDecay: 5,
    adoptionCost: 4500,
    isCustom: false,
    friendlyTo: ["bee", "ladybug", "fairy"],
    hostileTo: ["spider", "bird", "bat"],
  },
  {
    petId: "mouse",
    name: "Mouse",
    description: "A tiny squeaker with a big personality. Loves cheese!",
    emoji: "🐭",
    iconPath: "tbd.png",
    rarity: "common",
    hungerDecay: 5,
    hygieneDecay: 5,
    energyDecay: 5,
    funDecay: 5,
    adoptionCost: 4000,
    isCustom: false,
    friendlyTo: ["hamster", "rat", "guinea-pig"],
    hostileTo: ["cat", "snake", "owl"],
  },
  {
    petId: "rat",
    name: "Rat",
    description: "A smart and social rodent. Smarter than you think!",
    emoji: "🐀",
    iconPath: "rat.png",
    rarity: "common",
    hungerDecay: 5,
    hygieneDecay: 5,
    energyDecay: 5,
    funDecay: 5,
    adoptionCost: 4200,
    isCustom: false,
    friendlyTo: ["mouse", "hamster", "guinea-pig"],
    hostileTo: ["cat", "snake", "owl"],
  },
  {
    petId: "guinea-pig",
    name: "Guinea Pig",
    description: "A chunky squeaking potato. Wheeks for veggies!",
    emoji: "🐹",
    iconPath: "tbd.png",
    rarity: "common",
    hungerDecay: 5,
    hygieneDecay: 5,
    energyDecay: 5,
    funDecay: 5,
    adoptionCost: 6500,
    isCustom: false,
    friendlyTo: ["bunny", "hamster", "capybara", "mouse"],
    hostileTo: ["cat", "snake", "fox"],
  },
  {
    petId: "elephant",
    name: "Elephant",
    description: "A gentle giant with an incredible memory. Never forgets!",
    emoji: "🐘",
    iconPath: "tbd.png",
    rarity: "epic",
    hungerDecay: 2,
    hygieneDecay: 2,
    energyDecay: 2,
    funDecay: 2,
    adoptionCost: 88000,
    isCustom: false,
    friendlyTo: ["giraffe", "rhino", "hippo"],
    hostileTo: ["lion", "tiger"],
  },
  {
    petId: "tiger",
    name: "Tiger",
    description: "A powerful striped predator. Majestic and fierce!",
    emoji: "🐯",
    iconPath: "tbd.png",
    rarity: "epic",
    hungerDecay: 2,
    hygieneDecay: 2,
    energyDecay: 2,
    funDecay: 2,
    adoptionCost: 92000,
    isCustom: false,
    friendlyTo: ["lion", "panther", "leopard"],
    hostileTo: ["elephant", "buffalo", "monkey"],
  },
  {
    petId: "lion",
    name: "Lion",
    description: "The king of the jungle with a mighty roar!",
    emoji: "🦁",
    iconPath: "tbd.png",
    rarity: "epic",
    hungerDecay: 2,
    hygieneDecay: 2,
    energyDecay: 2,
    funDecay: 2,
    adoptionCost: 95000,
    isCustom: false,
    friendlyTo: ["tiger", "panther", "leopard"],
    hostileTo: ["hyena", "zebra", "buffalo"],
  },
  {
    petId: "bear",
    name: "Bear",
    description: "A big cuddly (but dangerous) forest dweller. Loves honey!",
    emoji: "🐻",
    iconPath: "tbd.png",
    rarity: "rare",
    hungerDecay: 3,
    hygieneDecay: 3,
    energyDecay: 3,
    funDecay: 3,
    adoptionCost: 45000,
    isCustom: false,
    friendlyTo: ["panda", "polar-bear", "grizzly"],
    hostileTo: ["wolf", "bee"],
  },
  {
    petId: "polar-bear",
    name: "Polar Bear",
    description: "A massive arctic hunter. Thrives in the cold!",
    emoji: "🐻‍❄️",
    iconPath: "tbd.png",
    rarity: "epic",
    hungerDecay: 2,
    hygieneDecay: 2,
    energyDecay: 2,
    funDecay: 2,
    adoptionCost: 98000,
    isCustom: false,
    friendlyTo: ["penguin", "king-penguin", "seal", "jack-frost"],
    hostileTo: ["seal", "walrus"],
  },
  {
    petId: "shark",
    name: "Shark",
    description:
      "A sleek ocean predator with rows of sharp teeth. Doo doo doo doo!",
    emoji: "🦈",
    iconPath: "shark.png",
    rarity: "rare",
    hungerDecay: 3,
    hygieneDecay: 3,
    energyDecay: 3,
    funDecay: 3,
    adoptionCost: 55000,
    isCustom: false,
    friendlyTo: ["orca", "megalodon"],
    hostileTo: ["blobfish", "seal", "penguin"],
  },
  {
    petId: "octopus",
    name: "Octopus",
    description: "An intelligent eight-armed cephalopod. Master of disguise!",
    emoji: "🐙",
    iconPath: "tbd.png",
    rarity: "rare",
    hungerDecay: 3,
    hygieneDecay: 3,
    energyDecay: 3,
    funDecay: 3,
    adoptionCost: 48000,
    isCustom: false,
    friendlyTo: ["squid", "crab", "blobfish"],
    hostileTo: ["shark", "orca"],
  },
  {
    petId: "doge",
    name: "Doge",
    description: "Much wow. Such pet. Very meme. Wow!",
    emoji: "🐕",
    iconPath: "tbd.png",
    rarity: "legendary",
    hungerDecay: 1,
    hygieneDecay: 1,
    energyDecay: 1,
    funDecay: 1,
    adoptionCost: 210000,
    isCustom: false,
    friendlyTo: ["pepe", "bob", "nyan-cat"],
    hostileTo: ["cheems"],
  },
  {
    petId: "nyan-cat",
    name: "Nyan Cat",
    description:
      "A pixelated pop-tart cat that flies through space! Rainbow trail included.",
    emoji: "🌈🐱",
    iconPath: "tbd.png",
    rarity: "legendary",
    hungerDecay: 1,
    hygieneDecay: 1,
    energyDecay: 1,
    funDecay: 1,
    adoptionCost: 225000,
    isCustom: false,
    friendlyTo: ["doge", "pepe", "grumpy-cat"],
    hostileTo: [],
  },
  {
    petId: "demon",
    name: "Demon",
    description: "A sinister being from the underworld. Handle with caution!",
    emoji: "😈",
    iconPath: "tbd.png",
    rarity: "epic",
    hungerDecay: 2,
    hygieneDecay: 2,
    energyDecay: 2,
    funDecay: 2,
    adoptionCost: 105000,
    isCustom: false,
    friendlyTo: ["krampus", "jack-o-lantern", "hellhound"],
    hostileTo: ["cupid", "unicorn", "angel"],
  },
  {
    petId: "ghost",
    name: "Ghost",
    description: "A friendly (or not so friendly) spirit. Boo!",
    emoji: "👻",
    iconPath: "tbd.png",
    rarity: "rare",
    hungerDecay: 3,
    hygieneDecay: 3,
    energyDecay: 3,
    funDecay: 3,
    adoptionCost: 52000,
    isCustom: false,
    friendlyTo: ["jack-o-lantern", "krampus", "skeleton"],
    hostileTo: ["dog", "cat"],
  },
];

export function getPetTypeById(petId: string): PetTypeData | undefined {
  return STATIC_PET_TYPES.find((pet) => pet.petId === petId);
}

export function getPetTypesByRarity(
  rarity: "common" | "uncommon" | "rare" | "epic" | "legendary",
): PetTypeData[] {
  return STATIC_PET_TYPES.filter((pet) => pet.rarity === rarity);
}

export function getAllPetTypes(): PetTypeData[] {
  return STATIC_PET_TYPES;
}

export function getCompatiblePets(petId: string): PetTypeData[] {
  const pet = getPetTypeById(petId);
  if (!pet) return [];

  return STATIC_PET_TYPES.filter((p) => pet.friendlyTo.includes(p.petId));
}

export function getIncompatiblePets(petId: string): PetTypeData[] {
  const pet = getPetTypeById(petId);
  if (!pet) return [];

  return STATIC_PET_TYPES.filter((p) => pet.hostileTo.includes(p.petId));
}

export function canPetsBreed(petId1: string, petId2: string): boolean {
  const pet1 = getPetTypeById(petId1);
  const pet2 = getPetTypeById(petId2);

  if (!pet1 || !pet2) return false;

  if (pet1.hostileTo.includes(petId2) || pet2.hostileTo.includes(petId1)) {
    return false;
  }

  return pet1.friendlyTo.includes(petId2) || pet2.friendlyTo.includes(petId1);
}
